### ISSUE TITLE
Event is not defined

### ISSUE THREAD

**Issue by jcmlumacad** [TMJPEngineering/angular-upload#1]
![event issue on tmj upload](https://user-images.githubusercontent.com/21231662/30008995-4bb358e0-9157-11e7-8914-a16ce7c599a4.gif)

**Comment by jcmlumacad** [comment]
Chrome seems okay but Firefox doesn't.

**Comment by rejtg21** [comment]
I see I miss declare the variable thank you for pointing this out. This was fix in https://github.com/TMJPEngineering/angular-upload/commit/440a68f9b9ff2f295f0c35e8742aef1789329477
