### ISSUE TITLE
Cannot do re upload without refreshing

### ISSUE THREAD

**Issue by jcmlumacad** [TMJPEngineering/angular-upload#2]
I upload the first file worked well. After that, I upload again the same file but it didn't upload without refreshing the page. @rejtg21

**Comment by rejtg21** [comment]
Yes it is prevented by default. It is now supported to upload the same file again on this commit https://github.com/TMJPEngineering/angular-upload/commit/aba8727fbfc1dfab372a63db09cf5ded64bc4829

**Comment by rejtg21** [comment]
please add an attribute allow-same-file="true" to work

**Comment by jcmlumacad** [comment]
Thanks for this. :+1: :100:
